### ISSUE TITLE
[Feature Request] sm_rankme_remove_duplicate Menu Admin

### ISSUE THREAD

**Issue by paulocrash** [rogeraabbccdd/Kento-Rankme#103]
Put the `sm_rankme_remove_duplicate` option on the **rankme menu**, I believe it would be perfect, clear of root access only.

**Comment by rogeraabbccdd** [comment]
I think we don't need this anymore since duplicate is fixed in 1dd4ef2c04a46881670c44678ffbb0dd1616f4e3.
