### ISSUE TITLE
I can't Change Prefix

### ISSUE THREAD

**Issue by Jozhoo** [rogeraabbccdd/Kento-Rankme#105]
Config Location: /home/hvh/serverfiles/csgo/addons/sourcemod/scripting/kento_rankme.sp
Default is : #define MSG "\x04 [RankMe] \x01\x0B\x01"
Mine: #define MSG "\x04 [Rank] \x01\x0B\x01"
After I restarted server. It's still show [RankMe]

**Comment by rogeraabbccdd** [comment]
Did you compile your plugin?

**Comment by Jozhoo** [comment]
wdym

**Comment by Jozhoo** [comment]
yes

**Comment by paulocrash** [comment]
I believe it would be perfect to have the option to edit this prefix in the translation or in the config it generates when first starting the server with the plugin. :)

**Comment by rogeraabbccdd** [comment]
Chat prefix has been added to translate files 06ec39373cf707510cb1c5c904e0f3d34c81956f
