### ISSUE TITLE
head attribute incorrect

### ISSUE THREAD

**Issue by niekcandaele** [rogeraabbccdd/Kento-Rankme#106]
I noticed the 'head' attribute doesn't seem correct. For example, there is a record for a player where headshots = 93 but head = 6.

I believe headshots = kills by headshot and head = hits in the head. By that logic, 'head' should always be equal or higher than 'headshots' (considering M4 does not always one shot in the head for example)

Maybe I am misunderstanding the meaning of these attributes?

![afbeelding](https://user-images.githubusercontent.com/22315101/56031351-8815a500-5d1f-11e9-8bab-57fb555ebf39.png)

Thanks!

**Comment by rogeraabbccdd** [comment]
dev branch will be merged to master branch soon.

**Comment by niekcandaele** [comment]
Thanks a lot! :D
