### ISSUE TITLE
Top noscope

### ISSUE THREAD

**Issue by rogeraabbccdd** [rogeraabbccdd/Kento-Rankme#107]
https://forums.alliedmods.net/showpost.php?p=2648256&postcount=654

**Comment by iGreen123** [comment]
it doesnt work man

> https://forums.alliedmods.net/showpost.php?p=2648256&postcount=654

**Comment by rogeraabbccdd** [comment]
3ad8a48df494ecc957da854eaeddfa4d56ba08fe
