### ISSUE TITLE
Question ! How do we get Client Ranks , trying on HexTags 

### ISSUE THREAD

**Issue by TandelK** [rogeraabbccdd/Kento-Rankme#108]
I am just trying to use RankMe with HexTags and i cannot see where i can get return of Client Rank , the RankMe Points is working perfectly. Just doesnt know how i can get Client Ranks in that plugin.

**Comment by rogeraabbccdd** [comment]
This is NOT rankme problem, please check your HexTags plugin configs.

**Comment by TandelK** [comment]
@rogeraabbccdd the thing is we are getting error with forwards of rankme. We can easily get Rankme points as forwards contains int as return of the points but as soon as we try to get Rank of the player we are having issues , it just keeps on showing -1. I just wanted to know how we can easily get a player rank with forwards.

**Comment by TandelK** [comment]
@rogeraabbccdd I require help regarding getting ranks via forwards , actually we tried to get Rank using the code but were not able to get rank and it always showed us -1

**Comment by TandelK** [comment]
We can talk on discord regarding this ? https://discord.gg/nnkGAg

**Comment by rogeraabbccdd** [comment]
I write a simple plugin to test rank forward, everything works fine
![csgo_ciKmUNwlGu](https://user-images.githubusercontent.com/15815422/57195750-c7cf5580-6f88-11e9-8557-88c389cb732d.png)

**Comment by rogeraabbccdd** [comment]
I'm 100% sure THIS IS NOT RANKME PROBLEM after I test hextags, your code is resetting the rank you get from rankme.

**Comment by rogeraabbccdd** [comment]
referenced above  by me was a mistake.
