### ISSUE TITLE
Most options to earn points

### ISSUE THREAD

**Issue by paulocrash** [rogeraabbccdd/Kento-Rankme#112]
Currently RankME Kento has option to earn points if he does the first kill, if he kills a player with noscope, etc.

I think you would be welcome if you had options like:

- DoubleKill
- TripleKill
- Domination
- Rampage
- MegaKill
- Ownage
- UltraKill
- KillingSpree
- MonsterKill
- Unstoppable
- GodLike

These options have in [Level Ranks](https://hlmod.ru/resources/levels-ranks-core.177/), I think it would be very interesting to put in RankME as well.

**Comment by rogeraabbccdd** [comment]
Multi-kills points has been suggested in #42
