### ISSUE TITLE
can you teach me any way to fix this unintelligible text？

### ISSUE THREAD

**Issue by LemonPAKA** [rogeraabbccdd/Kento-Rankme#113]
can you teach me any way to fix this unintelligible text？
https://imgur.com/O2W7fb2
https://imgur.com/7bMQvd3
https://imgur.com/GSkgs9t

**Comment by megoRU** [comment]
@LemonPAKA Hello

Enter the main phpmyAdmin menu and change the language. What's so complicated?

![image](https://user-images.githubusercontent.com/23276305/59549442-37f8d000-8f66-11e9-943d-c65ab77ef1bd.png)

**Comment by megoRU** [comment]
And also as I understood not that encoding in phpmyadmin

**Comment by LemonPAKA** [comment]
> And also as I understood not that encoding in phpmyadmin

I can't understand what you mean...My problem is....My other plugin's database use same setting and work well....but this one get  unintelligible text...feels weird
