### ISSUE TITLE
[Error Log] Query Fail

### ISSUE THREAD

**Issue by Drmohammad11** [rogeraabbccdd/Kento-Rankme#119]
hi my freind!!
i have more than 3000 player on rank me and i have this error log:
`[RankMe] Query Fail: Duplicate entry 'STEAM_ID_STOP_IGNORI' for key 'steam'`

thank you for support this plugin!!

**Comment by gabriel3l** [comment]
You should try to run this command:
`sm_rankme_remove_duplicate`

It removes the duplicated rows on the database.

**Comment by Drmohammad11** [comment]
0 duplicated rows :|

dont work

**Comment by gabriel3l** [comment]
Go in your database, find the rows with "STEAM_ID_STOP_IGNORI" as steamID and delete them manually

**Comment by Drmohammad11** [comment]
> Go in your database, find the rows with "STEAM_ID_STOP_IGNORI" as steamID and delete them manually

may server have 3000 players :/

**Comment by rogeraabbccdd** [comment]
You can run this SQL command/
```sql
DELETE FROM `rankme` WHERE steamID LIKE '%STEAM_ID_STOP_IGNOR%'
```
