### ISSUE TITLE
rankme_points_min_enabled and rankme_points_min has no effect, points can be negative

### ISSUE THREAD

**Issue by borzaka** [rogeraabbccdd/Kento-Rankme#122]
I wanted to start the ranking from 0 points, and I thought that it could never go down to negative values with the right settings, but it can:

`[RankMe] Attila from Hungary joined the server. (Pos 2 - -51 Points).`

My base config for the minimum point:
```
rankme_points_start "0"
rankme_points_min_enabled "1"
rankme_points_min "0"
```

My full Rankme config: https://pastebin.com/Q72TRXKh

Used plugins:
```
[SM] Listing 25 plugins:
  01 "Player Commands" (1.9.0.6281) by AlliedModders LLC
  02 "Reserved Slots" (1.9.0.6281) by AlliedModders LLC
  03 "Basic Chat" (1.9.0.6281) by AlliedModders LLC
  04 "Basic Info Triggers" (1.9.0.6281) by AlliedModders LLC
  05 "[Retakes] Autoplant" (2.3.0) by B3none
  06 "Anti-Flood" (1.9.0.6281) by AlliedModders LLC
  07 "[Retakes] Bombsite HUD" (2.5.0) by B3none
  08 "Admin Help" (1.9.0.6281) by AlliedModders LLC
  09 "Basic Votes" (1.9.0.6281) by AlliedModders LLC
  10 "Instant Defuse" (1.4) by Eyal282
  11 "Sound Commands" (1.9.0.6281) by AlliedModders LLC
  12 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
  13 "Basic Commands" (1.9.0.6281) by AlliedModders LLC
  14 "[Retakes] VIP Queue" (1.1.0) by B3none
  15 "CS:GO Retakes" (0.3.4+156) by splewis
  16 "Basic Comm Control" (1.9.0.6281) by AlliedModders LLC
  17 "AFK Manager" (4.3.0) by Rothgar
  18 "Fun Commands" (1.9.0.6281) by AlliedModders LLC
  19 "Basic Ban Commands" (1.9.0.6281) by AlliedModders LLC
  20 "RankMe" (3.0.3.Kento.31.2) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
  21 "Admin File Reader" (1.9.0.6281) by AlliedModders LLC
  22 "Client Preferences" (1.9.0.6281) by AlliedModders LLC
  23 "Fun Votes" (1.9.0.6281) by AlliedModders LLC
  24 "MyWeaponAllocator" (2.5) by shanapu
  25 "Admin Menu" (1.9.0.6281) by AlliedModders LLC
```

Sourcemod version: `1.9.0.6281`

**Comment by TandelK** [comment]
The reason why everyone in start default has 1000 points is due to this. I think it is better to keep in negative as people who are killing them get points added and who get killed gets no points reduced it will kind of unfair.

**Comment by borzaka** [comment]
I understand your reasons, but I still want 0 points as starting and minimum points, and there is a possibility in the config file to do that.

And somewhere between these lines, it should work, but it's doesn't. It doesn't set the client points to the minimum, when it's under the minimum.

My guess: maybe `g_aSession[victim][SCORE]` should be changed here as well;
`g_aSession[victim][SCORE] = g_PointsMin;`

https://github.com/rogeraabbccdd/Kento-Rankme/blob/aefdc97ee8aa244441032d0efb530b36fd5d7791/scripting/kento_rankme.sp#L919-L926

https://github.com/rogeraabbccdd/Kento-Rankme/blob/aefdc97ee8aa244441032d0efb530b36fd5d7791/scripting/kento_rankme.sp#L939-L946

https://github.com/rogeraabbccdd/Kento-Rankme/blob/aefdc97ee8aa244441032d0efb530b36fd5d7791/scripting/kento_rankme.sp#L1010-L1017

https://github.com/rogeraabbccdd/Kento-Rankme/blob/aefdc97ee8aa244441032d0efb530b36fd5d7791/scripting/kento_rankme.sp#L1025-L1032
