### ISSUE TITLE
Wrong player name character coding in MYSQL database

### ISSUE THREAD

**Issue by borzaka** [rogeraabbccdd/Kento-Rankme#126]
The displayed player names ingame in top lists are correct, but in the MYSQL database it's not. Therefore displaying on the website is full with uninterpretable characters.

Here are some examples:

Ingame:
![image](https://user-images.githubusercontent.com/1230402/66354612-aaeae400-e965-11e9-966b-c0b31eafa877.png)
As saved in the MYSQL database / showed on website: `anyukÃ¡m szeretÅ‘je`

Ingame:
![image](https://user-images.githubusercontent.com/1230402/66354643-c2c26800-e965-11e9-8643-03bebf10f39f.png)
As saved in the MYSQL database / showed on website: `â™ TÃ¶ReK`

Ingame:
![image](https://user-images.githubusercontent.com/1230402/66354667-dec60980-e965-11e9-8fdf-ceace8edaaae.png)
As saved in the MYSQL database / showed on website: `pÃ©csikesztyÅ±`

Ingame:
![image](https://user-images.githubusercontent.com/1230402/66354696-f69d8d80-e965-11e9-933a-f82414f19532.png)
As saved in the MYSQL database / showed on website: `E R C Ã‰ K Ã� âš¡`

DB collation: `utf8mb4_unicode_ci`
Webpage has `<meta charset="utf-8">`
Database connection `DB_CHARSET` is `utf8mb4`
`$this->db = new PDO(DB_TYPE . ':host=' . DB_HOST . ';dbname=' . DB_NAME . "; charset=" . DB_CHARSET, DB_USER, DB_PASS, $options);`

What DB collation should I use to store these names safely to display on a website?

What character encoding should I use on the website? The closest function is `utf8_decode`, but it's not perfect.

**Comment by ccsimplyspolit** [comment]
solution :
frite on 201 line in plugin.sm
```
		SQL_FastQuery(g_hStatsDb, "SET NAMES \"UTF8\"");
```
and compile it
![image](https://user-images.githubusercontent.com/29892758/79256068-0dcab400-7e90-11ea-88fd-dee79e9edff5.png)

**Comment by borzaka** [comment]
I would use `utf8mb4` instead of `utf8`.

My problem somewhat solved with settings in the DB (collate, charset, etc.) and some settings on the webapp. And probably SourceMod 1.10 is helped as well:
> Updated MySQL client library for utf8mb4 charset support.

**Comment by rogeraabbccdd** [comment]
https://github.com/rogeraabbccdd/Kento-Rankme/commit/94c517303a4443122aa4ff3b0b77d9ed88826953
