### ISSUE TITLE
Does anyone have a translation in pt?

### ISSUE THREAD

**Issue by geniobeast** [rogeraabbccdd/Kento-Rankme#128]
Can someone help me, does anyone have a translation in pt? I don't know how to translate

**Comment by paulocrash** [comment]
> Can someone help me, does anyone have a translation in pt? I do not know translate

@geniobeast I'm doing the translation for PT-BR, but I will only be able to finish it after the holidays.

As soon as possible I have a slightly translated version already.

Of course, would you like the PT-BR?

**Comment by rogeraabbccdd** [comment]
#130
