### ISSUE TITLE
problem error

### ISSUE THREAD

**Issue by piotrekkrol7** [rogeraabbccdd/Kento-Rankme#13]
`L 12/17/2016 - 11:15:26: [SM] Blaming: kento_rankme.smx
L 12/17/2016 - 11:15:26: [SM] Call stack trace:
L 12/17/2016 - 11:15:26: [SM]   [0] IsFakeClient
L 12/17/2016 - 11:15:26: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 11:16:09: [SM] Exception reported: Client 7 is not connected
L 12/17/2016 - 11:16:09: [SM] Blaming: kento_rankme.smx
L 12/17/2016 - 11:16:09: [SM] Call stack trace:
L 12/17/2016 - 11:16:09: [SM]   [0] IsFakeClient
L 12/17/2016 - 11:16:09: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 11:16:47: [SM] Exception reported: Client 7 is not connected
L 12/17/2016 - 11:16:47: [SM] Blaming: kento_rankme.smx
L 12/17/2016 - 11:16:47: [SM] Call stack trace:
L 12/17/2016 - 11:16:47: [SM]   [0] IsFakeClient
L 12/17/2016 - 11:16:47: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 11:17:25: [SM] Exception reported: Client 7 is not connected
L 12/17/2016 - 11:17:25: [SM] Blaming: kento_rankme.smx
L 12/17/2016 - 11:17:25: [SM] Call stack trace:
L 12/17/2016 - 11:17:25: [SM]   [0] IsFakeClient
L 12/17/2016 - 11:17:25: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 11:18:00: [SM] Exception reported: Client 10 is not connected
L 12/17/2016 - 11:18:00: [SM] Blaming: kento_rankme.smx
L 12/17/2016 - 11:18:00: [SM] Call stack trace:
L 12/17/2016 - 11:18:00: [SM]   [0] IsFakeClient
L 12/17/2016 - 11:18:00: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 11:18:48: [SM] Exception reported: Client 10 is not connected
L 12/17/2016 - 11:18:48: [SM] Blaming: kento_rankme.smx
L 12/17/2016 - 11:18:48: [SM] Call stack trace:
L 12/17/2016 - 11:18:48: [SM]   [0] IsFakeClient
L 12/17/2016 - 11:18:48: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 11:19:23: [SM] Exception reported: Client 12 is not connected
L 12/17/2016 - 11:19:23: [SM] Blaming: kento_rankme.smx
L 12/17/2016 - 11:19:23: [SM] Call stack trace:
L 12/17/2016 - 11:19:23: [SM]   [0] IsFakeClient
L 12/17/2016 - 11:19:23: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 11:20:06: [SM] Exception reported: Client 12 is not connected
L 12/17/2016 - 11:20:06: [SM] Blaming: kento_rankme.smx
L 12/17/2016 - 11:20:06: [SM] Call stack trace:
L 12/17/2016 - 11:20:06: [SM]   [0] IsFakeClient
L 12/17/2016 - 11:20:06: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
`

**Comment by JaroSound** [comment]
Same here :(

L 12/17/2016 - 14:08:56: [SM] Exception reported: Client 5 is not connected
L 12/17/2016 - 14:08:56: [SM] Blaming: rankme.smx
L 12/17/2016 - 14:08:56: [SM] Call stack trace:
L 12/17/2016 - 14:08:56: [SM]   [0] IsFakeClient
L 12/17/2016 - 14:08:56: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 14:09:31: [SM] Exception reported: Client 6 is not connected
L 12/17/2016 - 14:09:31: [SM] Blaming: rankme.smx
L 12/17/2016 - 14:09:31: [SM] Call stack trace:
L 12/17/2016 - 14:09:31: [SM]   [0] IsFakeClient
L 12/17/2016 - 14:09:31: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 14:10:11: [SM] Exception reported: Client 5 is not connected
L 12/17/2016 - 14:10:11: [SM] Blaming: rankme.smx
L 12/17/2016 - 14:10:11: [SM] Call stack trace:
L 12/17/2016 - 14:10:11: [SM]   [0] IsFakeClient
L 12/17/2016 - 14:10:11: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 14:11:11: [SM] Exception reported: Client 5 is not connected
L 12/17/2016 - 14:11:11: [SM] Blaming: rankme.smx
L 12/17/2016 - 14:11:11: [SM] Call stack trace:
L 12/17/2016 - 14:11:11: [SM]   [0] IsFakeClient
L 12/17/2016 - 14:11:11: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 14:12:45: [SM] Exception reported: Client 5 is not connected
L 12/17/2016 - 14:12:45: [SM] Blaming: rankme.smx
L 12/17/2016 - 14:12:45: [SM] Call stack trace:
L 12/17/2016 - 14:12:45: [SM]   [0] IsFakeClient
L 12/17/2016 - 14:12:45: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 14:15:13: Error log file session closed.
L 12/17/2016 - 14:18:43: SourceMod error session started
L 12/17/2016 - 14:18:43: Info (map "de_inferno") (file "errors_20161217.log")
L 12/17/2016 - 14:18:43: [SM] Exception reported: Client 5 is not connected
L 12/17/2016 - 14:18:43: [SM] Blaming: rankme.smx
L 12/17/2016 - 14:18:43: [SM] Call stack trace:
L 12/17/2016 - 14:18:43: [SM]   [0] IsFakeClient
L 12/17/2016 - 14:18:43: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 14:19:28: [SM] Exception reported: Client 5 is not connected
L 12/17/2016 - 14:19:28: [SM] Blaming: rankme.smx
L 12/17/2016 - 14:19:28: [SM] Call stack trace:
L 12/17/2016 - 14:19:28: [SM]   [0] IsFakeClient
L 12/17/2016 - 14:19:28: [SM]   [1] Line 1384, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::Event_RoundStart
L 12/17/2016 - 14:38:38: Error log file session closed.

**Comment by rogeraabbccdd** [comment]
I'm extremely busy this weekend...
I'll fix this as fast as I can.

**Comment by rogeraabbccdd** [comment]
Fixed.
