### ISSUE TITLE
[JUST DUMBNESS] cant find place where stats save

### ISSUE THREAD

**Issue by Apn1x** [rogeraabbccdd/Kento-Rankme#132]
I tought it was somewhere in the Phpmyadmin but I cant seem to find it does anyone know where I can find the data of the scores, for example give myself 69420 points

**Comment by borzaka** [comment]
Have you enabled MySQL in the plugin and added your DB/pass in SourceMod DB config? If not, then the default DB is SQLite, located:
`csgo/addons/sourcemod/data/sqlite/rankme.sq3`

**Comment by Apn1x** [comment]
oki thanks, second question is there a way to change my score. if so what program/website could do this?

**Comment by borzaka** [comment]
You can edit rankme.sq3 with a proper SQLite editor.
If you want a website to display the scores, you need to change to MySQL DB. And then you  can use Phpmyadmin, but you have write your own website to display the scores from rankme.
Or if you want to reset your score, there are commands for that.
