### ISSUE TITLE
Rankme Reset a rank

### ISSUE THREAD

**Issue by prT05** [rogeraabbccdd/Kento-Rankme#134]
Hello, I have a server, and I tryed to reset a player rank with sm_resetrank but I dont know what to put after the command on console! I tryed steam id, name and other but I cant reset a player rank! Can you help me? And another thing, the database how can I open it and read it, because when I try it have a lot of strange caracters!

Thanks in advice

**Comment by borzaka** [comment]
```
sm_resetrank //RankMe: Resets the rank of a player
sm_resetrank_all //RankMe: Resets the rank of all players
```

`sm_resetrank` parameter depends on this setting:
`rankme_rank_by     "0"    //Rank players by? 0 = STEAM:ID 1 = Name 2 = IP`
The default is steamid.
Usage: `sm_resetrank "STEAM_0:0:xxx"`

Database storage depends on this variable: 
`rankme_mysql     "0"    //Using MySQL? 1 = true 0 = false (SQLite)`
The default is SQLite, and you need an SQLite viewer/editor to read the DB.
Or if you use MySQL, a phpMyAdmin would be the best option to read your DB.

**Comment by prT05** [comment]
Really thanks
