### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by spyrek10** [rogeraabbccdd/Kento-Rankme#135]
Found these errors when compiling with sourcemod 1.10 6478 with latest includes from github.

> // \include\kento_rankme/rankme.inc(6) : error 001: expected token: "{", but found "struct"
// \include\kento_rankme/rankme.inc(7) : error 001: expected token: "public", but found "int"
// \include\kento_rankme/rankme.inc(8) : error 001: expected token: "}", but found "int"
// \include\kento_rankme/rankme.inc(137) : error 054: unmatched closing brace ("}")
// \include\kento_rankme/rankme.inc(139) : error 001: expected token: "{", but found "struct"
// \include\kento_rankme/rankme.inc(140) : error 001: expected token: "public", but found "int"
// \include\kento_rankme/rankme.inc(141) : error 001: expected token: "}", but found "int"
// \include\kento_rankme/rankme.inc(169) : error 021: symbol already defined: "GetData"
// \include\kento_rankme/rankme.inc(200) : error 021: symbol already defined: "Reset"
// \include\kento_rankme/rankme.inc(231) : error 054: unmatched closing brace ("}")
// \include\kento_rankme/rankme.inc(233) : error 001: expected token: "{", but found "struct"
// \include\kento_rankme/rankme.inc(234) : error 001: expected token: "public", but found "int"
// \include\kento_rankme/rankme.inc(235) : error 001: expected token: "}", but found "int"
// \include\kento_rankme/rankme.inc(245) : error 021: symbol already defined: "GetData"
// \include\kento_rankme/rankme.inc(255) : error 021: symbol already defined: "Reset"
// \include\kento_rankme/rankme.inc(265) : error 054: unmatched closing brace ("}")
// \include\kento_rankme/natives.inc(18) : warning 219: local variable "client" shadows a variable at a preceding level
// \include\kento_rankme/natives.inc(35) : error 017: undefined symbol "g_aStats"
// \include\kento_rankme/natives.inc(35) : warning 215: expression has no effect
// \include\kento_rankme/natives.inc(35) : error 001: expected token: ";", but found "]"
// \include\kento_rankme/natives.inc(35) : error 029: invalid expression, assumed zero
// \include\kento_rankme/natives.inc(35) : fatal error 190: too many error messages on one line
//

**Comment by rogeraabbccdd** [comment]
Please also update your `compile.exe`, `compile.dat` and `spcomp.exe` to 1.10 6478
