### ISSUE TITLE
Database problem (MySQL)

### ISSUE THREAD

**Issue by ruinedmoon** [rogeraabbccdd/Kento-Rankme#136]
I connect my database with server, change cvar to use mysql and plugin is working in game

but when i try to use !rank command or etc. i dont get any answer, but on console log i got this error
[kento_rankme.smx] [RankMe] Load Player Fail: Table 'deepfear_retakeRank.rankme' doesn't exist...

**Comment by musoviich** [comment]
[kento_rankme.smx] [RankMe] Query Fail: Table 'deepfear_retakeRank.rankme' doesn't exist
L 04/07/2020 - 15:00:03: [kento_rankme.smx] [RankMe] Check Unique Key Fail: Table 'deepfear_retakeRank.rankme' doesn't exist
L 04/07/2020 - 15:00:16: [kento_rankme.smx] [RankMe] Load Player Fail: Table 'deepfear_retakeRank.rankme' doesn't exist
