### ISSUE TITLE
unicode\russian encoding

### ISSUE THREAD

**Issue by ccsimplyspolit** [rogeraabbccdd/Kento-Rankme#141]
how fix that?
https://i.imgur.com/IiHZw9v.png

**Comment by ccsimplyspolit** [comment]
![image](https://user-images.githubusercontent.com/29892758/79250340-28e4f600-7e87-11ea-94ca-818f1d46a93e.png)

**Comment by ccsimplyspolit** [comment]
i found solution, please add

```
		SQL_FastQuery(g_hStatsDb, "SET NAMES \"UTF8\"");
```
on  201 line in  kento_rankme.sp
that forces utf-8, and fix any problems with russian, unicode characters.

**Comment by borzaka** [comment]
You could also check your settings in your webapp.
Tips to use:
- `define('DB_CHARSET', 'utf8mb4');`
- `$conn->set_charset("utf8mb4");`
- `$conn->query("SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci");`
- `charset=utf8mb4;` to the `new PDO()`

**Comment by rogeraabbccdd** [comment]
https://github.com/rogeraabbccdd/Kento-Rankme/commit/94c517303a4443122aa4ff3b0b77d9ed88826953

**Comment by zahti** [comment]
@ccsimplyspolit I am curious, what plugin are you using to display the data table on your website?

@rogeraabbccdd To apply this fix, should I just swap my compiled plugin to the most updated? The next time one of these players connect to the server, will the database be updated appropriately? Or will it make a new id/row?
![image](https://user-images.githubusercontent.com/38710634/83717360-c2ab6280-a5ef-11ea-8dc2-2c78b0b8c1fa.png)

**Comment by rogeraabbccdd** [comment]
```sql
UPDATE `rankme` set name = convert(cast(convert(name using latin1) as binary) using utf8) 
```

**Comment by zahti** [comment]
@rogeraabbccdd Should I run this query before or after using the updated plugin?
