### ISSUE TITLE
[error] it doesnt load

### ISSUE THREAD

**Issue by xKeksbyte** [rogeraabbccdd/Kento-Rankme#143]
AN ERROR HAS OCCURED [the index 'EnableGuardian' does not exist]

CALLSTACK
*FUNCTION [main()] InputRunScript line [1]

LOCALS
[this] TABLE
L 04/20/2020 - 16:25:56: World triggered "Round_Start"
L 04/20/2020 - 16:26:12: Starting Freeze period
Script not found (scripts/vscripts/cs_office/guardian_enable.nut)
Selected 2 hostage positions '0,4'
L 04/20/2020 - 16:26:12: World triggered "Match_Start" on "cs_office"
RecordSteamInterfaceCreation (PID 26554): SteamGameStats001 /

**Comment by rogeraabbccdd** [comment]
This is not related to rankme.
