### ISSUE TITLE
Stats supporting the new killfeed icons (Feature request)

### ISSUE THREAD

**Issue by HANSEMINATOR** [rogeraabbccdd/Kento-Rankme#147]
Since CSGO got the new killfeed icons, one of the requests I continuously get, is stats supporting these new killfeed icons. Basically logging:

- Kills through smoke
- Kills through walls
- No scopes (already implemented)

I know the new killfeed icons display more scenarious, and combinations even, but I think through the smoke - and perhaps walls - are the once really in demand.

Thanks for the great work.

**Comment by rogeraabbccdd** [comment]
Kills through smoke and flashed kill is added.

**Comment by HANSEMINATOR** [comment]
awesome-sauce, looking forward to trying it out!

**Comment by borzaka** [comment]
Nice, only through wall (penetrated) is missing, and everything is covered :)

Good job, thank you Kento!

**Comment by rogeraabbccdd** [comment]
Done
