### ISSUE TITLE
[Suggestion] Add melee weapons tracking

### ISSUE THREAD

**Issue by Sarrus1** [rogeraabbccdd/Kento-Rankme#161]
Hello,

I think it would be cool to track melee weapons kills aswell (weapon_hammer, weapon_axe, weapon_spanner) and even weapon_fists or weapon_breachcharge.

Thanks for the plugin!

**Comment by rogeraabbccdd** [comment]
`weapon_hammer`, `weapon_axe`, `weapon_spanner` and `weapon_fists` are already count as knife.
https://github.com/rogeraabbccdd/Kento-Rankme/blob/97216b225b81295c62d90183c63a0673e200bcc5/scripting/kento_rankme.sp#L1028-L1034

`weapon_breachcharge` is already added to weapon stats since .30 version.
