### ISSUE TITLE
Help with this pls

### ISSUE THREAD

**Issue by NaathySz** [rogeraabbccdd/Kento-Rankme#171]
I want reset just points. Its possible? 

I dont want reset kills, time etc, just the points.

**Comment by borzaka** [comment]
You have edit the database directly. There is no native command for that in RankMe.

**Comment by NaathySz** [comment]
> You have edit the database directly. There is no native command for that in RankMe.

Ok, no problem. But how i do it on database web page?

**Comment by borzaka** [comment]
With phpMyAdmin or any other web-based database manager. Even you can do it from console.

Find the right database with the all the player data, and there will be a column with the points.

**Comment by NaathySz** [comment]
> With phpMyAdmin or any other web-based database manager. Even you can do it from console.
> 
> Find the right database with the all the player data, and there will be a column with the points.

Sure. Thank you!

The last thing i need; have some way to transfeer the player datas to database? i never use the plugin with database before

**Comment by dennyb** [comment]
export the current stats to sql
see
`rankme_dump_db     "0"    //Dump the Database to SQL file? (required to be 1 if using the web interface and SQLite, case MySQL, it won't be dumped) 1 = true 0 = false`
and import this sql file into your database.

**Comment by NaathySz** [comment]
> export the current stats to sql see `rankme_dump_db "0" //Dump the Database to SQL file? (required to be 1 if using the web interface and SQLite, case MySQL, it won't be dumped) 1 = true 0 = false` and import this sql file into your database.

Im using MySQL, so i cant transfeer?

**Comment by dennyb** [comment]
Well, than export the sql and import into new mysql.
What's the problem now?
