### ISSUE TITLE
there is a error log , I need help

### ISSUE THREAD

**Issue by yeziuku** [rogeraabbccdd/Kento-Rankme#173]
[SM] Exception reported: Language phrase "ChatPrefix" not found (arg 5)
[SM] Blaming: kento_rankme . smx
[SM] call stack trace:
[SM] [0] Format
[SM] [1] Line 177，D:\csgoserver\csgoladdons\sourcemod\scripting\kento_rankme. sp : : OnPluginstart
[SM] Unable to load plugin "kento_rankme . smx" : Error detected in plugin startup (see error logs)

**Comment by yeziuku** [comment]
Line 177
/* Hide chat */
	hidechatcookie = RegClientCookie("rankme_hidechat", "Hide rankme chat messages", CookieAccess_Private);

	Format(MSG, sizeof(MSG), "%t", "Chat Prefix");

**Comment by rogeraabbccdd** [comment]
- Make sure you have installed translation files.
- Make sure your translation file versions are up to date (I only maintain en and zho).
- If your translation file format is not up to date, you can translate it by yourself.
