### ISSUE TITLE
Top Player Shows In hint box 

### ISSUE THREAD

**Issue by dani3lphp** [rogeraabbccdd/Kento-Rankme#174]
Top Player Shows In hint box even with  rankme_announcer_top_player_connect_hint "0". 
By default it come with 0, and it's lefted this way in the cfg, but it stills shows up when I start my server.

**Comment by rogeraabbccdd** [comment]
If you are using deathmatch plugin, there's nothing to do with rankme.
Check your deathmatch config instead.

**Comment by dani3lphp** [comment]
Yes, but where should I look in the deathmatch cfg? I got nothing there that should trigger this.
