### ISSUE TITLE
Add variable to translations?

### ISSUE THREAD

**Issue by Jury1x** [rogeraabbccdd/Kento-Rankme#175]
Hello, if I want to edit translation sentence for example in "Killing" I want to add how many points you have now and how many points the enemy you killed has, is there any shortest way to do so ? I have no idea how to link that variable, this ' "#format"	"{1:s},{2:d},{3:d},{4:s},{5:d}" ' doesnt tell me much about how to do the trick. Thank you

**Comment by rogeraabbccdd** [comment]
Google is always your best friend.
The question you are asking is the first result of Google search.
https://wiki.alliedmods.net/Translations_(SourceMod_Scripting)
![chrome_auHZq6plqP](https://user-images.githubusercontent.com/15815422/160986109-5ca24adf-2556-4710-bdb1-dcd31b97c771.png)
