### ISSUE TITLE
Welcome message chineese ?

### ISSUE THREAD

**Issue by P4R4DiSi4C** [rogeraabbccdd/Kento-Rankme#2]
Hello,
I downgraded to 1.8 to be able to use your plugin with mysql !
I finally achieved my goal. But I just wanted to be able why the welcome message prints in chineese or strange symbols ? Can I repair it ?

Thanks

**Comment by P4R4DiSi4C** [comment]
![ss 2016-11-19 at 01 31 04](https://cloud.githubusercontent.com/assets/17826095/20455448/8b8e4c42-ae5c-11e6-8106-a21b14a071b5.jpg)

**Comment by rogeraabbccdd** [comment]
delete translations/zho folder
