### ISSUE TITLE
Wrong Names

### ISSUE THREAD

**Issue by ekale007** [rogeraabbccdd/Kento-Rankme#20]
Hi,
i got the problem that the names got shown wrong in the Database and with that in the Webstats.

I tried everything fixing it in mysql alone but it doesnt change. What could i do to fix this im really out of ideas and dont know much about plugins or mysql.

**Comment by rogeraabbccdd** [comment]
I think I fix your problem in 3.0.3.Kento.21.
Please try it if you have time.
