### ISSUE TITLE
 Doubts with a RankME kento Version

### ISSUE THREAD

**Issue by paulocrash** [rogeraabbccdd/Kento-Rankme#22]
I wonder if you're still updating this rank?

I would also like to know if it has MySQL support, so I can create a website containing all the information of the players, a WebInterface.

**Comment by rogeraabbccdd** [comment]
I'm still updating this. 
This plugin support MySQL, so you can create a webinterface by urself or update old rankme webinterface for my rankme.

I update [this](https://forums.alliedmods.net/showpost.php?p=2417994&postcount=1205) webinterface for my rankme and use it [in my server](http://akami.twf.tw/rankme/).
