### ISSUE TITLE
Adding to !rank string

### ISSUE THREAD

**Issue by luckykev** [rogeraabbccdd/Kento-Rankme#25]
I have a quick question.

I am customizing the translations file in order to display the text I want when a person views their own rank by typing !rank.

I would like to know, is there is a command (ex. KDR of {8}) that lists the total headshots a person has?

I am trying to add to the string when a person types !rank to also say "you have {X} total headshots".

Does this exist?

**Comment by rogeraabbccdd** [comment]
https://forums.alliedmods.net/showpost.php?p=2496495&postcount=204

**Comment by luckykev** [comment]
Since the OP didn't help me at all, is there anyone that may know? Obviously I wouldn't be posting here if I knew how to do it myself.

Just PM me on AlliedModders, thanks!
