### ISSUE TITLE
Strange Hit Stats

### ISSUE THREAD

**Issue by T1MOXA** [rogeraabbccdd/Kento-Rankme#31]
In my statistics there are strange numbers...
Here's an example:

shots":"1210",
"hits":"452"

"head":"653",
"chest":"856",
"stomach":"255",
"left_arm":"31",
"right_arm":"139",
"left_leg":"68",
"right_leg":"71"

`[{"id":"9045","steam":"STEAM_1:0:***","name":"","lastip":"***","score":"438","kills":"164","deaths":"31","assists":"0","suicides":"0","tk":"0","shots":"1210","hits":"452","headshots":"147","connected":"6505","rounds_tr":"65","rounds_ct":"144","lastconnect":"1491500764","knife":"1","glock":"0","hkp2000":"0","usp_silencer":"0","p250":"0","deagle":"0","elite":"0","fiveseven":"0","tec9":"0","cz75a":"0","revolver":"0","nova":"0","xm1014":"0","mag7":"0","sawedoff":"0","bizon":"0","mac10":"0","mp9":"0","mp7":"0","ump45":"0","p90":"0","galilar":"0","ak47":"159","scar20":"0","famas":"0","m4a1":"0","m4a1_silencer":"3","aug":"0","ssg08":"1","sg556":"0","awp":"0","g3sg1":"0","m249":"0","negev":"0","hegrenade":"0","flashbang":"0","smokegrenade":"0","inferno":"0","decoy":"0","taser":"0","head":"653","chest":"856","stomach":"255","left_arm":"31","right_arm":"139","left_leg":"68","right_leg":"71","c4_planted":"0","c4_exploded":"0","c4_defused":"0","ct_win":"1","tr_win":"61","hostages_rescued":"0","vip_killed":"0","vip_escaped":"0","vip_played":"0","mvp":"30","damage":"122170"}]`

http://SSMaker.ru/58d99c13/

How could this happen ?

**Comment by rogeraabbccdd** [comment]
Try rankme_rank_cache 0
