### ISSUE TITLE
Server isn't starting with h3bu's DeathMatch plugin.

### ISSUE THREAD

**Issue by SmXme** [rogeraabbccdd/Kento-Rankme#33]
Hi,
So i've a problem : 
When i'm using your plugin with the H3bu's DM, sqlite local mode, there is no problem, all is fine. (except an errorlog about a message that i commented in the dm plugin config file).

But, when i'm trying to switch into the mysql mode, the server can't start, and the logs are saying this : 
L 04/18/2017 - 08:00:04: SourceMod log file session started (file "L20170418.log") (Version "1.8.0.5947")
L 04/18/2017 - 08:00:04: -------- Mapchange to de_dust2 --------
L 04/18/2017 - 08:00:04: [GEOIP] GeoIP database info: GEO-106FREE 20161004 Build 1 Copyright (c) 2016 MaxMind 
L 04/18/2017 - 08:00:04: [deathmatch.smx] Dynamic Hooks not found! Resuming without Dhooks features
L 04/18/2017 - 08:00:34: SourceMod log file session started (file "L20170418.log") (Version "1.8.0.5947")
L 04/18/2017 - 08:00:34: -------- Mapchange to de_dust2 --------
L 04/18/2017 - 08:00:34: [GEOIP] GeoIP database info: GEO-106FREE 20161004 Build 1 Copyright (c) 2016 MaxMind 
L 04/18/2017 - 08:00:34: [deathmatch.smx] Dynamic Hooks not found! Resuming without Dhooks features

H3bus Plugin link : https://forums.alliedmods.net/showthread.php?t=233685
Thanks ! 
(steam : popof59)

**Comment by rogeraabbccdd** [comment]
This is not my rankme error, looks like you didn't install dhooks in your server.
https://forums.alliedmods.net/showthread.php?t=180114
