### ISSUE TITLE
Blank name

### ISSUE THREAD

**Issue by ownage13** [rogeraabbccdd/Kento-Rankme#44]
So I have one of my players who's name comes in blank on the webpage of this plugin. Do you guys have any idea what could be causing that? He happens to be rank 1 in our database and I want to be sure his name is visible for everyone to see.

https://imgur.com/a/Zjq2j

**Comment by ownage13** [comment]
nevermind i figured it out. Said user has <windows> in his name and the "< >" part of his name makes his name invisible in the database. Maybe something that needs to be fixed in the future? (:

**Comment by szogi1910** [comment]
https://github.com/ToxicRevolution/CSGORankMeWeb/issues
