### ISSUE TITLE
Dobbel Reg

### ISSUE THREAD

**Issue by spot88** [rogeraabbccdd/Kento-Rankme#45]
Sometimes players get's double registered. Any reason why? Same Steamid and nick.

**Comment by spot88** [comment]
'id' is different but rest is the same.

**Comment by spot88** [comment]
Anyone?

**Comment by rogeraabbccdd** [comment]
Sorry I'm busy in my another project now, I will review this plugin if I have time.

**Comment by PaulVlas** [comment]
Instead of making the steamid a text key in the SQL database you should make it a varchar with a unique key so duplicates cannot be made.

**Comment by rogeraabbccdd** [comment]
If you set your steamid to unique key but `rankme_rankbots` is 1, you will get an error spam.
![srcds_c023gLP07p](https://user-images.githubusercontent.com/15815422/56142475-54fa3c80-5fd1-11e9-9a57-82a1890f9a05.png)
