### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by spot88** [rogeraabbccdd/Kento-Rankme#5]
Add a config file so it's possible to adjust settings like name of table that is created. 
Very useful when you are running multiple servers on the same database.

**Comment by rogeraabbccdd** [comment]
Config will create automatically, you can find it in csgo/cfg/sourcemod/kento.rankme.cfg
You can change sql table name with cvar "rankme_sql_table".

**Comment by spot88** [comment]
Inside config file right?

**Comment by rogeraabbccdd** [comment]
Yes.
