### ISSUE TITLE
Some convar changes use wrong types

### ISSUE THREAD

**Issue by shavitush** [rogeraabbccdd/Kento-Rankme#51]
i.e.

https://github.com/rogeraabbccdd/Kento-Rankme/blob/141b872f0a31575579730aeece7ea524a86e02f9/gameserver/scripting/kento_rankme.sp#L2271-L2273

Should be an integer

**Comment by rogeraabbccdd** [comment]
Fixed in dev branch, and will merge to master branch soon.
