### ISSUE TITLE
Invalid query Handle c29c80e2 (error: 4)

### ISSUE THREAD

**Issue by fkMain** [rogeraabbccdd/Kento-Rankme#59]
Logs:

L 03/28/2018 - 17:49:32: [SM] Exception reported: Invalid query Handle c29c80e2 (error: 4)
L 03/28/2018 - 17:49:32: [SM] Blaming: kento_rankme.smx
L 03/28/2018 - 17:49:32: [SM] Call stack trace:
L 03/28/2018 - 17:49:32: [SM]   [0] SQL_FetchString
L 03/28/2018 - 17:49:32: [SM]   [1] Line 1401, C:\Users\LIB\Downloads\aaa\sourcemod-1.8.0-git6027-windows\addons\sourcemod\scripting\include\kento_rankme/cmds.inc::SQL_RankCallback

**Comment by cRUSHER-HLG** [comment]
Invalid query handle are mostly thrown when a plugin cant proceed a sql query. The logs shows exactly what i sayed. SQL_FetchString cant be excecuted so with a really high probability you have an issue with your sql server.

**Comment by rogeraabbccdd** [comment]
Answered by @cRUSHER-HLG
