### ISSUE TITLE
Webdesign

### ISSUE THREAD

**Issue by spot88** [rogeraabbccdd/Kento-Rankme#6]
Integrate a webdesign to use all your gathered data, like assists \ death \ hs and so on. 
Here is a easy one, made by scratch based on the orginal plugin RankMe. 
http://games01.tafjord.no/files/pages/retake.php

**Comment by rogeraabbccdd** [comment]
I'm not planning to make a new rankme webinterface or something.
I'm using [nguyenbaodanh's rankme webinterface](https://forums.alliedmods.net/showpost.php?p=2417994&postcount=1205) in my server, with my webupdate files.
