### ISSUE TITLE
Array Issue

### ISSUE THREAD

**Issue by TandelK** [rogeraabbccdd/Kento-Rankme#61]
Getting the following error on the server and also have issues after performing Rank Reset of the whole Server. 

[SM] Exception reported: Array index is out of bounds
L 07/07/2018 - 19:15:58: [SM] Blaming: kento_rankme.smx
L 07/07/2018 - 19:15:58: [SM] Call stack trace:
L 07/07/2018 - 19:15:58: [SM]   [1] Line 2006, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::EventPlayerHurt
L 07/07/2018 - 19:18:47: [SM] Exception reported: Array index is out of bounds
L 07/07/2018 - 19:18:47: [SM] Blaming: kento_rankme.smx
L 07/07/2018 - 19:18:47: [SM] Call stack trace:
L 07/07/2018 - 19:18:47: [SM]   [1] Line 2006, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\kento_rankme.sp::EventPlayerHurt
L 07/07/2018 - 19:19:43: [SM] Exception reported: Array index is out of bounds
L 07/07/2018 - 19:19:43: [SM] Blaming: kento_rankme.smx
L 07/07/2018 - 19:19:43: [SM] Call stack trace:

**Comment by rogeraabbccdd** [comment]
Fixed
