### ISSUE TITLE
Missing GeoIP

### ISSUE THREAD

**Issue by vtrbh** [rogeraabbccdd/Kento-Rankme#77]
I've heard that it comes with sourcemod and ive just installed both sourcemod and metamod, so those are updated for sure. But when i try to launch the server with this plugin i get this error:

Unable to load plugin "kento_rankme.smx": Required extension "GeoIP" file("geoip.ext") not running

i took a look and the file is there at "csgo\addons\sourcemod\extensions"

Any idea on how can i fix this?

**Comment by rogeraabbccdd** [comment]
Please use commamd `sm exts list` in your server and paste outputs here, thank you.

**Comment by rogeraabbccdd** [comment]
Closed because GeoIP is sourcemod problem.
