### ISSUE TITLE
Language phrase "Match Wins" not found..

### ISSUE THREAD

**Issue by Waltsh** [rogeraabbccdd/Kento-Rankme#80]
Hello. After i type !statsme it does that.

L 09/14/2018 - 23:01:39: [SM] Exception reported: Language phrase "Match Wins" not found (arg 17)
L 09/14/2018 - 23:01:39: [SM] Blaming: kento_rankme.smx
L 09/14/2018 - 23:01:39: [SM] Call stack trace:
L 09/14/2018 - 23:01:39: [SM]   [0] Format
L 09/14/2018 - 23:01:39: [SM]   [1] Line 1604, I:\csgodev\server\csgo\addons\sourcemod\scripting\include\kento_rankme/cmds.inc::SQL_StatsMeCallback

**Comment by rogeraabbccdd** [comment]
Fixed in 0d276847db7dc5506595d2dc5e3388d6d952dc37
