### ISSUE TITLE
SQL_StatsMe2Callback

### ISSUE THREAD

**Issue by szogi1910** [rogeraabbccdd/Kento-Rankme#82]
L 10/08/2018 - 15:48:08: [kento_rankme.smx] [RankMe] Query Fail: Column count doesn't match value count at row 1
L 10/08/2018 - 15:53:15: [SM] Exception reported: Current result set has no fetched rows
L 10/08/2018 - 15:53:15: [SM] Blaming: kento_rankme.smx
L 10/08/2018 - 15:53:15: [SM] Call stack trace:
L 10/08/2018 - 15:53:15: [SM]   [0] SQL_FetchInt
L 10/08/2018 - 15:53:15: [SM]   [1] Line 1670, E:\Download\firefox\scripting\scripting\include\kento_rankme/cmds.inc::SQL_StatsMe2Callback
L 10/08/2018 - 15:53:19: [SM] Exception reported: Current result set has no fetched rows
L 10/08/2018 - 15:53:19: [SM] Blaming: kento_rankme.smx
L 10/08/2018 - 15:53:19: [SM] Call stack trace:
L 10/08/2018 - 15:53:19: [SM]   [0] SQL_FetchInt
L 10/08/2018 - 15:53:19: [SM]   [1] Line 1670, E:\Download\firefox\scripting\scripting\include\kento_rankme/cmds.inc::SQL_StatsMe2Callback

**Comment by rogeraabbccdd** [comment]
Hi, I just tested with latest dev branch and statsme2 works fine for me.

**Comment by szogi1910** [comment]
Hi, the error was probably caused by the update of the plugin
The database had an old column "rank" after it was removed, the problem disappeared
