### ISSUE TITLE
Problem with MySQL!

### ISSUE THREAD

**Issue by Munoon** [rogeraabbccdd/Kento-Rankme#84]
Hi mate! I have a problem that in database (MySQL) writing only nickname, steamid, last ip (not sure that it his last ip) and start points (1000 points). After that player no more supported. Like if he earn 3000 points on server writed that he had 4000 points but in database writes still 1000 points.
[MySQL screanshot](https://user-images.githubusercontent.com/43534008/47526473-7abb4a00-d8a8-11e8-8bf4-ac4f4aa47e65.png)

**Comment by rogeraabbccdd** [comment]
I can't reproduce your problem.
Try change `rankme_rank_cache` to `0` in your config.

**Comment by Munoon** [comment]
it was already setted...

**Comment by rogeraabbccdd** [comment]
Can you tell me how to reproduce your problem?
I have tried a fresh install on my test server, everything worked.

**Comment by Munoon** [comment]
ok, send me please config which you tested and which worked. I think im idiot and have mistake in configuration but cant find it...

**Comment by Munoon** [comment]
and would be grate if you could send me your tested .smx plugin too

**Comment by Munoon** [comment]
well, im dowloaded older version of your plugin and everything work corrrectly. 
Version: [Kento-Rankme-master 1.zip](https://github.com/rogeraabbccdd/Kento-Rankme/files/2529027/Kento-Rankme-master.1.zip)
