### ISSUE TITLE
Same players in database

### ISSUE THREAD

**Issue by Munoon** [rogeraabbccdd/Kento-Rankme#85]
Hi! I have a problem that I have same players in database with same steam id, score, nickname and so on. I have plugin version 3.0.3.Kento.27.2. You may take a look to understand problem here: http://train4game.com/rankme/leaderboards.php

**Comment by Munoon** [comment]
Also have error logs on server:
L 10/31/2018 - 22:53:57: [SM] Exception reported: Array index out-of-bounds (index 8, limit 8)
L 10/31/2018 - 22:53:57: [SM] Blaming: kento_rankme.smx
L 10/31/2018 - 22:53:57: [SM] Call stack trace:
L 10/31/2018 - 22:53:57: [SM]   [1] Line 1885, C:\Users\LIB\Downloads\aaa\sourcemod-1.8.0-git6027-windows\addons\sourcemod\scripting\kento_rankme.sp::EventPlayerHurt

**Comment by rogeraabbccdd** [comment]
please update your plugin to latest version, it should fix the problem in your error log.
