### ISSUE TITLE
Last update error!

### ISSUE THREAD

**Issue by rebelkat** [rogeraabbccdd/Kento-Rankme#92]
Hello!

Please see line 26...
You need to add one more '0', to it.
The base table is 82 column, but you ad 1 more column on line 553 - breachcharge.

the base error i got was:

L 12/12/2018 - 11:47:08: [kento_rankme.smx] [RankMe] Query Fail: Column count doesn't match value count at row 1

**Comment by rogeraabbccdd** [comment]
It should be fixed now, please update your plugin.

**Comment by superblack4** [comment]
OMG i got this error too. I thought I am the only one who got this error :v

**Comment by superblack4** [comment]
It is ok brother ur work is great :))
