### ISSUE TITLE
[BUG] Log Error Translation

### ISSUE THREAD

**Issue by paulocrash** [rogeraabbccdd/Kento-Rankme#98]
After I updated to the latest version I started to receive the following error in the servers log:
```
L 02/10/2019 - 00:29:34: [SM] Fatal error encountered parsing translation file "kento.rankme.phrases.txt"
L 02/10/2019 - 00:29:34: [SM] Error (line 0, column 0): Stream failed to open
L 02/10/2019 - 00:39:56: Error log file session closed.
```
[errors_20190210.log](https://github.com/rogeraabbccdd/Kento-Rankme/files/2848500/errors_20190210.log)

**Comment by rogeraabbccdd** [comment]
en and zho translations are always up to date.
If you're using other languages you have to check the translation file by yourself.
And don't forget to create a pull request after you fixed your problem.
